modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

issueTrackerURL="https://github.com/Ceziak/ricedelight/issues"


[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

displayURL="https://github.com/Ceziak/ricedelight"
authors="Ceziak"

enumExtensions="META-INF/enumextensions.json"

description='''
A Farmer's Delight add-on expanding the possibilities of rice.

Rice Delight adds new ingredients, blocks, recipes, crops and meals based
around rice, bell peppers and other foods.
'''


[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
reason="Rice Delight requires NeoForge."
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"


[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
reason="Rice Delight is made for Minecraft 1.21.1."
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"


[[dependencies.${mod_id}]]
modId="farmersdelight"
type="required"
reason="Rice Delight is a Farmer's Delight add-on."
versionRange="[1.3.2,2)"
ordering="AFTER"
side="BOTH"