# Rice Delight mod metadata

modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

# Where users can report problems
issueTrackerURL="https://github.com/Ceziak/ricedelight/issues"


# --------------------------------------------------
# Rice Delight
# --------------------------------------------------

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

# Page displayed in the Mods menu
displayURL="https://github.com/Ceziak/ricedelight"

authors="Ceziak"

description='''
A Farmer's Delight add-on expanding upon the possibilities of rice.

Rice Delight adds new ingredients, blocks, recipes and meals based around
rice.
'''


# --------------------------------------------------
# NeoForge dependency
# --------------------------------------------------

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
reason="Rice Delight is built for NeoForge."
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"


# --------------------------------------------------
# Minecraft dependency
# --------------------------------------------------

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
reason="Rice Delight is made for Minecraft 1.21.1."
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"


# --------------------------------------------------
# Farmer's Delight dependency
# --------------------------------------------------

[[dependencies.${mod_id}]]
modId="farmersdelight"
type="required"
reason="Rice Delight is an add-on for Farmer's Delight and uses its recipes and systems."
versionRange="[1.3.2,2)"
ordering="AFTER"
side="BOTH"